AWSTemplateFormatVersion: 2010-09-09
Description: aws-apig-swagger-generator
Parameters:
  BucketName:
    Description: Name of bucket to host swagger. Account number will be appended to this name.
    Type: String
    Default: swagger-server
Resources:
  SwaggerHostBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration: {} #TODO
      Tags:
        - Key: ApplicationName
          Value: aws-apig-swagger-generator
      WebsiteConfiguration: {} #TODO
  SwaggerHostPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SwaggerHostBucket
      PolicyDocument: {} #TODO
  APIGMonitorRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: String
      EventBusName: String
      EventPattern: Json
      Name: String
      RoleArn: String
      ScheduleExpression: String
      State: String
      Targets:
        - Target
  SwaggerGeneratorLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code: {} #required TODO
      Description: Lambda function to generate swagger yaml from apig deployment
      Environment:
        Variables:
          bucketName: !Ref SwaggerHostBucket
      FunctionName: SwaggerGeneratorLambda
      Handler: index.handler
      Role: !Ref LambdaExecutionRole
      Runtime: nodejs12.x
      Tags:
        - Key: ApplicationName
          Value: aws-apig-swagger-generator
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Effect: 'Allow'
                Resource: '*'
          PolicyName: 'lambda'
      Path: /
      RoleName: LambdaExecutionRole
      Tags:
        - Key: ApplicationName
          Value: aws-apig-swagger-generator

Transform:

Outputs:
